-- CreateTable
CREATE TABLE `EvaluationResult` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `title` VARCHAR(191) NOT NULL,
    `pitch` VARCHAR(191) NOT NULL,
    `problem` VARCHAR(191) NOT NULL,
    `solution` VARCHAR(191) NOT NULL,
    `targetAudience` VARCHAR(191) NOT NULL,
    `businessModel` VARCHAR(191) NOT NULL,
    `competition` VARCHAR(191) NULL,
    `experience` VARCHAR(191) NULL,
    `education` VARCHAR(191) NULL,
    `skills` VARCHAR(191) NULL,
    `founderRole` VARCHAR(191) NULL,
    `traction` VARCHAR(191) NULL,
    `mvpReady` VARCHAR(191) NULL,
    `vision` VARCHAR(191) NULL,
    `feasibility` INTEGER NOT NULL,
    `marketPotential` INTEGER NOT NULL,
    `competitionScore` INTEGER NOT NULL,
    `scalability` INTEGER NOT NULL,
    `executionDifficulty` INTEGER NOT NULL,
    `verdict` VARCHAR(191) NOT NULL,
    `summary` VARCHAR(191) NOT NULL,
    `nextSteps` VARCHAR(191) NOT NULL,
    `techStack` VARCHAR(191) NULL,
    `fundingStage` VARCHAR(191) NULL,
    `investorMatches` VARCHAR(191) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
